// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9g1e5LLLDS4TGJiaFCSEyH
// Component: 2QrXQ3Lsq6zG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Switch } from "@/fragment/components/switch"; // plasmic-import: dH6_VlwkAh4P/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 9g1e5LLLDS4TGJiaFCSEyH/projectcss
import sty from "./PlasmicProfilePrescriptionSettings.module.css"; // plasmic-import: 2QrXQ3Lsq6zG/css

createPlasmicElementProxy;

export type PlasmicProfilePrescriptionSettings__VariantMembers = {};
export type PlasmicProfilePrescriptionSettings__VariantsArgs = {};
type VariantPropType = keyof PlasmicProfilePrescriptionSettings__VariantsArgs;
export const PlasmicProfilePrescriptionSettings__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProfilePrescriptionSettings__ArgsType = {};
type ArgPropType = keyof PlasmicProfilePrescriptionSettings__ArgsType;
export const PlasmicProfilePrescriptionSettings__ArgProps =
  new Array<ArgPropType>();

export type PlasmicProfilePrescriptionSettings__OverridesType = {
  root?: Flex__<"div">;
  _switch?: Flex__<typeof Switch>;
  switch2?: Flex__<typeof Switch>;
};

export interface DefaultProfilePrescriptionSettingsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProfilePrescriptionSettings__RenderFunc(props: {
  variants: PlasmicProfilePrescriptionSettings__VariantsArgs;
  args: PlasmicProfilePrescriptionSettings__ArgsType;
  overrides: PlasmicProfilePrescriptionSettings__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "_switch.checked",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "switch2.checked",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___7Un2B)}
      >
        <Switch
          data-plasmic-name={"_switch"}
          data-plasmic-override={overrides._switch}
          checked={generateStateValueProp($state, ["_switch", "checked"])}
          className={classNames("__wab_instance", sty._switch)}
          onCheckedChange={generateStateOnChangeProp($state, [
            "_switch",
            "checked"
          ])}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__xxC7M
          )}
        >
          {
            "\u063a\u06cc\u0631\u0641\u0639\u0627\u0644 \u06a9\u0631\u062f\u0646 SMS \u0646\u0647\u0627\u06cc\u06cc \u0633\u0627\u0632\u06cc \u0646\u0633\u062e\u0647"
          }
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___62Cd1)}
      >
        <Switch
          data-plasmic-name={"switch2"}
          data-plasmic-override={overrides.switch2}
          checked={generateStateValueProp($state, ["switch2", "checked"])}
          className={classNames("__wab_instance", sty.switch2)}
          onCheckedChange={generateStateOnChangeProp($state, [
            "switch2",
            "checked"
          ])}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zhBdF
          )}
        >
          {
            "\u0648\u06cc\u0631\u0627\u06cc\u0634 \u0627\u0637\u0644\u0627\u0639\u0627\u062a \u0627\u062d\u0631\u0627\u0632 \u0647\u0648\u06cc\u062a"
          }
        </div>
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "_switch", "switch2"],
  _switch: ["_switch"],
  switch2: ["switch2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  _switch: typeof Switch;
  switch2: typeof Switch;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProfilePrescriptionSettings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProfilePrescriptionSettings__VariantsArgs;
    args?: PlasmicProfilePrescriptionSettings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicProfilePrescriptionSettings__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      PlasmicProfilePrescriptionSettings__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProfilePrescriptionSettings__ArgProps,
          internalVariantPropNames:
            PlasmicProfilePrescriptionSettings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProfilePrescriptionSettings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfilePrescriptionSettings";
  } else {
    func.displayName = `PlasmicProfilePrescriptionSettings.${nodeName}`;
  }
  return func;
}

export const PlasmicProfilePrescriptionSettings = Object.assign(
  // Top-level PlasmicProfilePrescriptionSettings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    _switch: makeNodeComponent("_switch"),
    switch2: makeNodeComponent("switch2"),

    // Metadata about props expected for PlasmicProfilePrescriptionSettings
    internalVariantProps: PlasmicProfilePrescriptionSettings__VariantProps,
    internalArgProps: PlasmicProfilePrescriptionSettings__ArgProps
  }
);

export default PlasmicProfilePrescriptionSettings;
/* prettier-ignore-end */
