// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9g1e5LLLDS4TGJiaFCSEyH
// Component: 1AR8vXE8xbWC

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 9g1e5LLLDS4TGJiaFCSEyH/projectcss
import sty from "./Plasmicدمهتجوزنسخه.module.css"; // plasmic-import: 1AR8vXE8xbWC/css

createPlasmicElementProxy;

export type Plasmicدمهتجوزنسخه__VariantMembers = {};
export type Plasmicدمهتجوزنسخه__VariantsArgs = {};
type VariantPropType = keyof Plasmicدمهتجوزنسخه__VariantsArgs;
export const Plasmicدمهتجوزنسخه__VariantProps = new Array<VariantPropType>();

export type Plasmicدمهتجوزنسخه__ArgsType = {};
type ArgPropType = keyof Plasmicدمهتجوزنسخه__ArgsType;
export const Plasmicدمهتجوزنسخه__ArgProps = new Array<ArgPropType>();

export type Plasmicدمهتجوزنسخه__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultدمهتجوزنسخهProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmicدمهتجوزنسخه__RenderFunc(props: {
  variants: Plasmicدمهتجوزنسخه__VariantsArgs;
  args: Plasmicدمهتجوزنسخه__ArgsType;
  overrides: Plasmicدمهتجوزنسخه__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmicدمهتجوزنسخه__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmicدمهتجوزنسخه__VariantsArgs;
    args?: Plasmicدمهتجوزنسخه__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmicدمهتجوزنسخه__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      Plasmicدمهتجوزنسخه__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmicدمهتجوزنسخه__ArgProps,
          internalVariantPropNames: Plasmicدمهتجوزنسخه__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmicدمهتجوزنسخه__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName =
      "Plasmic\u062f\u0645\u0647\u062a\u062c\u0648\u0632\u0646\u0633\u062e\u0647";
  } else {
    func.displayName = `Plasmicدمهتجوزنسخه.${nodeName}`;
  }
  return func;
}

export const Plasmicدمهتجوزنسخه = Object.assign(
  // Top-level Plasmicدمهتجوزنسخه renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for Plasmicدمهتجوزنسخه
    internalVariantProps: Plasmicدمهتجوزنسخه__VariantProps,
    internalArgProps: Plasmicدمهتجوزنسخه__ArgProps
  }
);

export default Plasmicدمهتجوزنسخه;
/* prettier-ignore-end */
